### ISSUE TITLE
Scrobbles are mostly missing

### ISSUE THREAD

**Issue by mlms13** [NeApp/neon-extension#18]
Occasionally tracks get scrobbled, but a majority seem to be missing. I'm using Firefox 57 and plugin version 1.5.8.

From the log:

<img width="1231" alt="screen shot 2017-12-03 at 20 49 58" src="https://user-images.githubusercontent.com/1105543/33535565-91bca426-d86b-11e7-99f5-42968749e9a8.png">

It looks like something is treating `<@moz-etensions://` as part of a relative URL?

**Comment by fuzeman** [comment]
Is there any trend to the music that is (or isn't) being scrobbled? have you uploaded this music? or are you streaming this music with a Google Play Music subscription?

This track is scrobbling correctly for me, so there is likely a communication issue with the Google Play Music Metadata API. I'm working on some error reporting improvements which may help identify this issue, will likely have these changes released on the beta channel later today.

------------

> It looks like something is treating <@moz-etensions:// as part of a relative URL?

I think this is just something Firefox does with all addons, it appears to be just a display issue.

**Comment by mlms13** [comment]
I'm using a Google Play Music subscription. I forget which tracks I originally uploaded, but at least some of the ones that failed to scrobble are not songs that I uploaded.

It actually looks like it may not be hit-or-miss, it may be that it just stopped working completely. Maybe it was a temporary glitch... I'll try scrobbling the same tracks again in a couple hours to see if it works better.

**Comment by mlms13** [comment]
Yeah, this completely went away. Not sure what the actual issue was, but it doesn't need any attention.
