### ISSUE TITLE
Blows up firefox memory usage

### ISSUE THREAD

**Issue by g2p** [NeApp/neon-extension#19]
This is on Firefox nightly.
After scrobbling a few tracks, the extension shows up with a few gigabytes in about:memory reports.

**Comment by fuzeman** [comment]
Looking at the memory usage of Firefox Developer Edition (v58.0b9) shows the extension has a ~150MB peak when GPM (Google Play Music) is first opened, dropping down to ~40MB after about a minute. *(see graphs below)*

Maybe there is currently an issue with Firefox Nightly that is causing this? the extension uses IndexedDB quite heavily for metadata and session storage, so an issue with IndexedDB could impact performance quite a bit.

I'll have a look at Firefox Nightly later today to see if I can reproduce this issue.

----------------------------

**Extension Disabled**
![neon-disabled](https://user-images.githubusercontent.com/526664/33633370-6e86bd00-da75-11e7-9598-4c697c9798ad.gif)

**Extension Enabled**
![neon-enabled](https://user-images.githubusercontent.com/526664/33633382-7dfe7840-da75-11e7-82fd-b039065b6974.gif)

**Scrobble**
![neon-scrobble](https://user-images.githubusercontent.com/526664/33633391-848269c4-da75-11e7-9398-725e1ae644ed.gif)
