### ISSUE TITLE
Absolutely no scrobbling coming from Firefox

### ISSUE THREAD

**Issue by T6A52** [NeApp/neon-extension#22]
I've been using this app for almost a year now, and for the longest time I didn't have any issues with scrobbling, it was ridiculously reliable (this was back when it was still Google Music Scrobbler). However, I recently updated Firefox (the issue first started with 59, but I'm at 60 now and the issue persists), and with it the version of the app to Neon 1.8.0.299, and since then I have been unable to get the app to scrobble to last.fm at all. No notifications are sent to my last.fm page, no tracks are being scrobbled, it's like the app isn't even there, even though I've enabled both last.fm and GPM in the options menu bar. Does anyone know what I can do to fix this problem?

Thanks!

**Comment by fuzeman** [comment]
Have you checked the settings under `Addons -> Neon -> Options`?

Your settings should have been migrated after updating to 1.x, but there is a chance something went wrong during this process. Ensure that Last.fm and Google Play Music has been enabled in the addon options, and try re-authenticating your Last.fm account.

-------------

If you are still experiencing issues with scrobbling:

1. Close Google Play Music (if it's currently open)
2. Set the "Log Level" options to Debug (under the General, Google Play Music and Last.fm pages)
3. Open Google Play Music, and the web console (Ctrl + Shift + K)
4. Start playing a track
5. Copy (or screenshot) the messages displayed in the web console (may need to wait a minute for everything to initialize first)

**Comment by T6A52** [comment]
I reset all of the possible add on options probably upwards of 10 times, just to ensure that I wasn't accidentally glossing over everything. Enabled the necessary apps; reauthenticated my last.fm account - absolutely nothing.

What page am I supposed to have open, for the web console debugging - GPM or the options page for Neon?

**Comment by fuzeman** [comment]
> What page am I supposed to have open, for the web console debugging - GPM or the options page for Neon?

Open the web console on the Google Play Music tab.

**Comment by T6A52** [comment]
The following is what the log said:



CSI/tbsd_
cb=gapi.loaded_0:338:127
CSI/_tbnd
cb=gapi.loaded_0:338:127
Loading failed for the <script> with source “https://ssl.google-analytics.com/ga.js”.
listen:1
paper-toolbar is deprecated. Please use app-layout instead!
listen.js:3937:435
Initializing "activity" service "neon-extension-source-googlemusic:activity"...
common.js:1:65271
Initialized "activity" service "neon-extension-source-googlemusic:activity"
common.js:1:65271
Initializing "library" service "neon-extension-source-googlemusic:library"...
common.js:1:65271
Initialized "library" service "neon-extension-source-googlemusic:library"
common.js:1:65271
Waiting for page to load...
common.js:1:65271
paper-toolbar is deprecated. Please use app-layout instead!
listen.js:3937:435
Could not find style data in module named iron-flex
listen.js:369:460
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Page loaded
googlemusic.js:1:12717
Bound to "neon.event"
googlemusic.js:1:8559
Bound to "neon.request"
shim.js:1:6661
Unable to fetch library: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 
DOMException: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
shim.js:1:7841
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: try {

(function injectPageScriptAPI(scr....
widget:1
Attempt to set a forbidden header was denied: Connection
1907778746-lcs_client_bin.js:114:385
Unable to fetch library: Request timeout 
Error: Request timeout
Stack trace:
Ci9t/value/</u<@moz-extension://779dc87e-90b2-4116-aeed-7b68bafd6de3/source/googlemusic/googlemusic.js:1:9925
googlemusic.js:1:2641
Attempt to set a forbidden header was denied: Connection

**Comment by fuzeman** [comment]
> ```
> DOMException: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
> ```

It looks like this error might be caused by a corrupt Firefox profile, possibly caused by downgrading Firefox or opening your profile in multiple versions of Firefox. You may be able to confirm this with https://firefox-storage-test.glitch.me/ (no idea how reliable this is though) or test the addon with a new Firefox profile (details [here](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)).

You could then [refresh](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) your profile, to create a new profile with [bookmarks, history, cookies, etc..](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings#w_firefox-will-save-these-items) from your existing profile.

------------

https://github.com/dfahlander/Dexie.js/issues/298
https://github.com/FooSoft/yomichan/issues/76

https://bugzilla.mozilla.org/show_bug.cgi?id=1425146
https://greasyfork.org/en/forum/discussion/6663/state-of-denial

**Comment by T6A52** [comment]
Refreshing Firefox seems to have done the trick - it seems my music listening history does get tracked now. Thanks so much for your help!

**Comment by fuzeman** [comment]
No problem, glad it's working now.
