### ISSUE TITLE
Google Play Music: Scrobbling when listening on repeat

### ISSUE THREAD

**Issue by MikeF-** [NeApp/neon-extension#24]
Listening on repeat at Google Play Music does not scrobble tracks after the first one.
It does not seem to matter whether you queue the same track or just put repeat track on.

It would be nice if scrobbling happens before the entire track is over. It is common in many scrobblers to scrobble after 50% listened.

**Comment by fuzeman** [comment]
I'll take a look later this week, shouldn't be too hard to resolve this.

**Comment by fuzeman** [comment]
Fixed in [v1.9.0](https://github.com/NeApp/neon-extension/releases/tag/v1.9.0)
