### ISSUE TITLE
Support for YouTube Music

### ISSUE THREAD

**Issue by RayChimera** [NeApp/neon-extension#26]
Are there plans for it?

**Comment by fuzeman** [comment]
Next on my list, will have a look after v2.0 of the extension is released.

**Comment by fuzeman** [comment]
Available in [v2.1.0-beta.1](https://github.com/NeApp/neon-extension/releases/tag/v2.1.0-beta.1), will be releasing it to stable after some more testing.

**Comment by fuzeman** [comment]
Released [v2.1.0-beta.2](https://github.com/NeApp/neon-extension/releases/tag/v2.1.0-beta.2) with some improvements to *YouTube Music* support.

> **Changed**
> 
>  - Improvements to metadata `resolveArtists` and `resolveTitle` methods
> 
> **Fixed**
> 
>  - **YouTube Music:** Issues with activity detection on Firefox

**Comment by fuzeman** [comment]
Released to stable channel in [v2.1.0](https://github.com/NeApp/neon-extension/releases/tag/v2.1.0).

**Comment by Slaedr** [comment]
Firstly, thanks for the great extension. Works great with Google Play Music. However, it's not scrobbling from Youtube music. I've enabled it in settings. Is there anything else I need to do to enable it?
