### ISSUE TITLE
YouTube Music -> LastFM doesn't work

### ISSUE THREAD

**Issue by Smile4ever** [NeApp/neon-extension#34]
It doesn't scrobble.

Bound to "neon.request" Shim.js:1:6430
Waiting for player to load... Shim.js:1:3542
Initializing "activity" service "neon-extension-source-youtubemusic:activity"... Common.js:31:40302
Initialized "activity" service "neon-extension-source-youtubemusic:activity" Common.js:31:40302
Bound to "neon.event" Common.js:31:40302
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. music_polymer.js:3359:45
TypeError: "document.getElementsByClassName(...)[0].getElementsByClassName(...)[0] is undefined"
    getYoutubeMusic moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:99
    getSong moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:81
    run moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:7
    setInterval handler* moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:176
main.js:64:17
[Youtube NonStop v0.5.1] Observing video player! autoconfirm.js:36:13
Player loaded Shim.js:1:3780
[ytmusic-player-bar] Duplicate node addition for: 
<ytmusic-player-bar class="style-scope ytmusic-app" slot="player-bar" repeat-mode_="NONE" style="--ytmusic-player-bar-ful…rogress-bar-inset:20px;" player-page-open_="">
Common.js:1:7392
TypeError: "document.getElementsByClassName(...)[0].getElementsByClassName(...)[0] is undefined"
    getYoutubeMusic moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:99
    getSong moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:81
    run moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:7
    setInterval handler* moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:176
main.js:64:17
TypeError: "document.getElementsByClassName(...)[0].getElementsByClassName(...)[0] is undefined"
    getYoutubeMusic moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:99
    getSong moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:81
    run moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:7
    setInterval handler* moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:176
main.js:64:17
TypeError: "document.getElementsByClassName(...)[0].getElementsByClassName(...)[0] is undefined"
    getYoutubeMusic moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:99
    getSong moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:81
    run moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:7
    setInterval handler* moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:176
main.js:64:17
Started progress emitter Main.js:1:27175
Received player state: 
Object { duration: 253, state: 1, time: 0.064104, url: "https://www.youtube.com/watch?list=RDAMVMOCepTmI6nUg&v=OCepTmI6nUg" }
Main.js:1:27283
TypeError: "document.getElementsByClassName(...)[0].getElementsByClassName(...)[0] is undefined"
    getYoutubeMusic moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:99
    getSong moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:81
    run moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:7
    setInterval handler* moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:176
main.js:64:17
TypeError: "document.getElementsByClassName(...)[0].getElementsByClassName(...)[0] is undefined"
    getYoutubeMusic moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:99
    getSong moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:81
    run moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:7
    setInterval handler* moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:176
main.js:64:17
TypeError: "document.getElementsByClassName(...)[0].getElementsByClassName(...)[0] is undefined"
    getYoutubeMusic moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:99
    getSong moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:81
    run moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:7
    setInterval handler* moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:176
main.js:64:17
TypeError: "document.getElementsByClassName(...)[0].getElementsByClassName(...)[0] is undefined"
    getYoutubeMusic moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:99
    getSong moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:81
    run moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:7
    setInterval handler* moz-extension://a7a5ff0b-31f6-4ef5-bef7-6bcdf97e8edb/main.js:176
main.js:64:17

**Comment by fuzeman** [comment]
Fixed in [v2.2.0-beta.6](https://github.com/RadonApp/radon-extension/releases/tag/v2.2.0-beta.6), will release it to the stable channel later today.

**Comment by Smile4ever** [comment]
I can confirm the fix works, thank you.
