### ISSUE TITLE
Google Play Music: Metadata lookup failures

### ISSUE THREAD

**Issue by Terrance** [NeApp/neon-extension#35]
Most scrobbles aren't going through, and instead log in the console:

> Unable to fetch metadata for item `Object { _values: {…}, _metadata: {…} }` : undefined

(where `_values` has the correct information)

Occasionally it works though -- I'm guessing this is to do with matched vs. unmatched uploads.

**Comment by Eagle3386** [comment]
@fuzeman any update on this?

**Comment by fuzeman** [comment]
Everything should be working again in [v2.3.1](https://github.com/RadonApp/radon-extension/releases/tag/v2.3.1).
